pipeline:
  test:
    image: node:10.16.0-slim
    commands:
      - yarn install
      - yarn lint

  build:
    image: node:10.16.0-slim
    commands:
      - apt-get update && apt-get install -y git
      - git checkout $DRONE_COMMIT_BRANCH
      - CI=false yarn build
    when:
      branch:
        - subscription
        - demo
      event:
        - push

  docker_publish:
    image: plugins/docker
    repo: goharbor.erxes.io/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}
    registry: goharbor.erxes.io
    dockerfile: Dockerfile
    secrets:
      - docker_username
      - docker_password
    tags:
      - ${DRONE_BRANCH}
    when:
      branch:
        - subscription
        - demo
      event:
        - push
